name: ci

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo check
        run: cargo check --all-targets
      - name: Cargo test
        run: cargo test --all-targets -- --nocapture
      - name: Cargo clippy
        run: cargo clippy --all-targets -- -D warnings