name: ci

on:
  push:
  pull_request:

jobs:
  native-quality:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-14
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Cargo check
        run: cargo check --all-targets
      - name: Cargo test
        run: cargo test --all-targets -- --nocapture
      - name: Cargo clippy
        run: cargo clippy --all-targets -- -D warnings

  cross-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            experimental: false
          - target: armv7-unknown-linux-gnueabihf
            experimental: false
          - target: riscv64gc-unknown-linux-gnu
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install cross
        run: cargo install --locked cross
      - name: Cross build
        run: cross build --release --target ${{ matrix.target }}

  windows-cross-build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: aarch64-pc-windows-msvc
            experimental: false
          - target: i686-pc-windows-msvc
            experimental: false
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build target
        run: cargo build --release --target ${{ matrix.target }}
